### ISSUE TITLE
Elevation should be 8

### ISSUE THREAD

**Issue by AlexandrePalo** [mxck/react-native-material-menu#10]
Hello,

Thanks for your component.
In order to stay consistent, according to the [Material guide concerning elevation](https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-elevation-android) the elevation should be 8 and not 2 by default.

So, on android:
`{
elevation: 8
}`

And on IOS:
`{
shadowOpacity: 0.192,
shadowRadius: 4.32,
      shadowOffset: {
        height: 4.8,
      }
}`

Moreover, the elevation value should be a props by itself because can be a major styling props to ensure consistency with other UX components. For android, the props is straight forward. For IOS, formulas are:
`
      shadowOpacity: 0.0015 * elevation + 0.18,
      shadowRadius: 0.54 * elevation,
      shadowOffset: {
        height: 0.6 * elevation,
      }
`

I can present a PR if you want :)

Bye

**Comment by mxck** [comment]
@AlexandrePalo hi! Yes, you can make PR. 👍

**Comment by Noitidart** [comment]
> Hello,
> 
> Thanks for your component.
> In order to stay consistent, according to the [Material guide concerning elevation](https://material.io/guidelines/material-design/elevation-shadows.html#elevation-shadows-elevation-android) the elevation should be 8 and not 2 by default.
> 
> So, on android:
> `{ elevation: 8 }`
> 
> And on IOS:
> `{ shadowOpacity: 0.192, shadowRadius: 4.32, shadowOffset: { height: 4.8, } }`
> 
> Moreover, the elevation value should be a props by itself because can be a major styling props to ensure consistency with other UX components. For android, the props is straight forward. For IOS, formulas are:
> `shadowOpacity: 0.0015 * elevation + 0.18, shadowRadius: 0.54 * elevation, shadowOffset: { height: 0.6 * elevation, }`
> 
> I can present a PR if you want :)
> 
> Bye

What is the shadowOffset `width`?
