### ISSUE TITLE
it's not working according to index.

### ISSUE THREAD

**Issue by varunSuccessive** [mxck/react-native-material-menu#104]
i have list of array and I have to open pop Menu  according to index but it's always appearing for last index value. So how to specify to appear index wise.

**Comment by vismayainnow8** [comment]
yes .. i too found the same issue

**Comment by UnSensei** [comment]
declare the menu = []
and when you try to show or close, pass the unique id like this.menu[id].show();

**Comment by wiztensai** [comment]
> 
> 
> declare the menu = []
> and when you try to show or close, pass the unique id like this.menu[id].show();

no, it cannot. i tried it. i use useRef hook.
TypeError: undefined is not an object (evaluating 'refTopRightMenu["2"].current')

**Comment by mxck** [comment]
Now in version 2.0.0 you do not need to use ref.
