### ISSUE TITLE
How to work with hook

### ISSUE THREAD

**Issue by rajush1** [mxck/react-native-material-menu#105]
import React, { useRef } from 'react';

import { View, Text, StyleSheet ,ImageBackground} from 'react-native';
import Menu, { MenuItem, MenuDivider } from 'react-native-material-menu';

/**
 * Note:
 * This demo uses latest version of expo with react hooks support.
 * You can read about hooks at https://reactjs.org/docs/hooks-intro.html
 */

function App() {
  const menu = useRef();

  const hideMenu = () => menu.current.hide();

  const showMenu = () => menu.current.show();

  return (
    <View style={styles.container}>
      <Menu ref={menu} button={<ImageBackground style={{height:50,width:50}} source={require('https://i.ya-webdesign.com/images/three-dots-menu-png-5.png')} onPress={showMenu} />}>
        <MenuItem onPress={hideMenu}>Menu item 1</MenuItem>
        <MenuItem onPress={hideMenu}>Menu item 2</MenuItem>
        <MenuItem onPress={hideMenu} disabled>
          Menu item 3
        </MenuItem>
        <MenuDivider />
        <MenuItem onPress={hideMenu}>Menu item 4</MenuItem>
      </Menu>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default App;

Fixed it

**Comment by mxck** [comment]
I update README with working example.
