### ISSUE TITLE
On Android, not matching native PopupMenu look

### ISSUE THREAD

**Issue by Noitidart** [mxck/react-native-material-menu#12]
Hi there,

I am using this on android currently to try to acheive the native PopupMenu. This is a screenshot of native PopupMenu:

![popupmenu-android-case](https://user-images.githubusercontent.com/6372489/36038006-35cccaa0-0d73-11e8-92b7-f9d6133b581d.png)

And this is how it looks when I use react-native-material-menu out of the box on Android:

![react-native-material-menu-android-case](https://user-images.githubusercontent.com/6372489/36038011-3a8c6d84-0d73-11e8-92db-84e26a8c5e16.png)

We see on touch, there is no ripple. We need to use `<TouchableNativeFeedback>` I think.

We also see that the item on press is not flush against the top. There seems to be a gap.

Is there a way to fix this on my side, or do we need to edit the lib?

Other minor issues that I can fix with style prop, but would be ideal if it matched native android:

* Font size of menu item
* Font color of menu item
* Too much (by like 4dpi) horizontal margin on menu item's
* Elevation shadow, but i see issue for this already - https://github.com/mxck/react-native-material-menu/issues/10

It would be so awesome if this looked perfect like the native PopupMenu on Android out of the box (hence the name of the lib :) )

Ideally I tried to find a native lib for Android PopupMenu in react-native but I can't. :( And I'm not experience with native ui modules yet in RN :(

**Comment by Noitidart** [comment]
Ohhh shoot I just read the readme, this does match spec for web material menu. Shoot. Maybe this is not an issue. However, this module is pretty much I would say 100% used on mobile, so it might be nice to offer the mobile material spec. :)

**Comment by mxck** [comment]
@Noitidart temporary you can pass styles and textStyles props to MenuItem.
Also. Than version of android you use and device? This is pure android?

**Comment by mxck** [comment]
And I think use TouchableNativeFeedback is good idea.

**Comment by Noitidart** [comment]
Thanks @mxck!! I use Android 4.4.4 and Android 6.0.

**Comment by Noitidart** [comment]
@mxck I just found a native solution is already built into react-native, so we can leave your module as is, so it gives the "material-web" style.
