### ISSUE TITLE
Unable to change the position of the menu.

### ISSUE THREAD

**Issue by PoojaVM** [mxck/react-native-material-menu#16]
I have implemented the menu as you have suggested in the usage section here - https://github.com/mxck/react-native-material-menu and it works fine.

The issue I am facing is regarding the position of the menu opened. I am able to locate the show menu text wherever I want on the screen but the menu always opens in the left top corner. I want it to open in the top right corner.
Please let me know how I can achieve this as I see the same can be done looking at the gif of the demo you have attached for the same?

**Comment by mxck** [comment]
@PoojaVM hi! Can you post some you code sample?

**Comment by reddyabhishek** [comment]
If I just copy-paste  your code, the Show Menu button appears in the top-left part of the screen. How to put it in the top-right?

**Comment by mxck** [comment]
You can place menu where you want using ```style``` prop or by wrapping with View component from React-Native.

I update example, so you can check full code.

**Comment by PoojaVM** [comment]
Hey @mxck , I did not look into it afterwards. I will try it out since you have updated the example. Thank you.

**Comment by serolgames** [comment]
Hello, 5 years later the issue is still the same. There is no example. I tried everything to change the position to the right but nothing work. What's the trick ?

**Comment by Jessyaw** [comment]
have the same issue...i need to position it in bottom center but unable to position it

**Comment by houdaddou** [comment]
Hi how please should I open the menu in top left position, there's nothing in doc 
        <View
          style={{
            height: "100%",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Menu
            style={{
              width: 200,
              shadowOffset: {
                width: 0,
                height: 1,
              },
              shadowRadius: 5,
              shadowColor: "rgba(0, 0, 0, 0.25)",
              shadowOpacity: 1,
              elevation: 5,
            }}
            visible={isDialogVisible}
            onRequestClose={hideMenu}
            anchor={
              <IconButton callback={showMenu} themeColor="black">
                <SVGActions height={20} width={20} fill="balck" />
              </IconButton>
            }
          >
            <SpacedView
              style={{
                flexDirection: "column",
              }}
            >
              <IconButton
                horizontal={"xxs"}
                callback={hideMenu}
                themeColor="black"
              >
                <SVGActions height={20} width={20} fill="balck" />
              </IconButton>
              <MenuItem
                onPress={() =>
                  removeFromFavourite("traffic", "lines", favorite.id)
                }
                style={{
                  marginTop: "-10%",
                }}
              >
                <IconButton
                  buttonLabel="Supprimer le favori"
                  themeColor="#C10F0F"
                  textSize={14}
                  spacerSize="xs"
                >
                  <SVGDelete height={20} width={20} fill="#C10F0F" />
                </IconButton>
              </MenuItem>
            </SpacedView>
          </Menu>
        </View>

**Comment by PoojaVM** [comment]
@houdaddou ,

To view the menu in the top right corner, change your view styles as follows

`
      <View
        style={{
          height: '100%',
          alignItems: 'flex-end',
          justifyContent: 'flex-start',
          margin: 10,
        }}>
`

**Comment by houdaddou** [comment]
It worked for me when i did the changes in the menu style
