### ISSUE TITLE
peer dependencies

### ISSUE THREAD

**Issue by r3wt** [mxck/react-native-material-menu#20]
```
npm WARN react-native-material-menu@0.3.1 requires a peer of react@>= 16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-material-menu@0.3.1 requires a peer of react-native@>= 0.54.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by mxck** [comment]
@r3wt in readme I have a note:
> ⚠️ Starting from version 0.3.0 minimum required react-native version is 0.54.

If you have older react-native version use 0.2 version.

You can install older version like this:
- By yarn `yarn add react-native-material-menu@~0.2.0` 
- By npm `npm install --save react-native-material-menu@~0.2.0`

Also you can upgrade your react-native project by this [guide](https://facebook.github.io/react-native/docs/upgrading.html)

If you upgrade your project or downgrade to 0.2.x version and error still exists please send your `react-native info`

**Comment by mxck** [comment]
Sorry. I din not see that `none is installed`. Are you sure that you are installing the package in react-native project folder?

**Comment by r3wt** [comment]
lol, yes of course i installed it in my project. imo, this is a bad/wrong use of peer dependencies. i ended up just using a different library instead *shrugs*

On Apr 24, 2018 10:45 PM, Maksim <notifications@github.com> wrote:

Sorry. I din not see that none is installed. Are you sure that you are installing the package in react-native project folder?

**Comment by mxck** [comment]
> this is a bad/wrong use of peer dependencies
Why? :)

>  ended up just using a different library instead *shrugs*
Ok! This is your choice :)

Also seems this is npm issue, recommended way `rm -rf node_modules` and install `npm install`.  Everything works.

Can you try before use other library? :)

**Comment by r3wt** [comment]
> Why?
npm doens't install peer dependencies anymore, so you should avoid declaring peer dependencies in your package, and declare them as dependencies instead.

> Can you try it before use other library? :)
I'm sorry, i already moved to the other library. This is just a side gig i work at nights. I simply don't have the time to wait
