### ISSUE TITLE
error rendering the menu

### ISSUE THREAD

**Issue by yordanisgomez** [mxck/react-native-material-menu#21]
Hello,
after the onPress Menu button is raised, I get this error:

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `Menu`.

This error is located at:
    in RCTView (at View.js:71)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at Menu.js:172)
    in RCTView (at View.js:71)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at Menu.js:164)
    in RCTView (at View.js:71)
    in View (at Menu.js:163)
    in TouchableWithoutFeedback (at Menu.js:162)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:122)
    in AppContainer (at Modal.js:238)
    in RCTView (at View.js:71)
    in View (at Modal.js:257)
    in RCTModalHostView (at Modal.js:244)
    in Modal (at Menu.js:161)
    in RCTView (at View.js:71)
    in View (at Menu.js:158)
    in Menu (at Todo.js:41)
    in RCTView (at View.js:71)
    in View (at ListItem.react.js:455)
    in RCTView (at View.js:71)
    in View (at ListItem.react.js:470)
    in RCTView (at View.js:71)
    in View (at ListItem.react.js:483)
    in TouchableWithoutFeedback (at RippleFeedbackIOS.react.js:283)
    in RippleFeedbackIOS (at ListItem.react.js:490)
    in RCTView (at View.js:71)
    in View (at ListItem.react.js:502)
    in ListItem (at Todo.js:34)
    in Todo (at TodoListContainer.js:18)
    in RCTView (at View.js:71)
    in View (at VirtualizedList.js:1363)
    in CellRenderer (at VirtualizedList.js:556)
    in RCTScrollContentView (at ScrollView.js:717)
    in RCTScrollView (at ScrollView.js:811)
    in ScrollView (at VirtualizedList.js:871)
    in VirtualizedList (at FlatList.js:634)
    in FlatList (at TodoListContainer.js:16)
    in RCTView (at View.js:71)
    in View (at TodoListContainer.js:11)
    in TodoList (created by Connect(TodoList))
    in Connect(TodoList) (at LoggedInHome.js:61)
    in RCTView (at View.js:71)
    in View (at LoggedInHome.js:59)
    in RCTView (at View.js:71)
    in View (at Screen.js:28)
    in Unknown (at LoggedInHome.js:58)
    in Home (at withNavigation.js:21)
    in withNavigation(Home) (created by Connect(withNavigation(Home)))
    in Connect(withNavigation(Home)) (at SceneView.js:31)
    in SceneView (at CardStack.js:405)
    in RCTView (at View.js:71)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at Card.js:26)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:436)
    in RCTView (at View.js:71)
    in View (at CardStack.js:365)
    in RCTView (at View.js:71)
    in View (at CardStack.js:364)
    in CardStack (at CardStackTransitioner.js:97)
    in RCTView (at View.js:71)
    in View (at Transitioner.js:187)
    in Transitioner (at CardStackTransitioner.js:49)
    in CardStackTransitioner (at StackNavigator.js:60)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:216)
    in NavigationContainer (at SceneView.js:31)
    in SceneView (at TabView.js:82)
    in RCTView (at View.js:71)
    in View (at TabView.js:81)
    in RCTView (at View.js:71)
    in View (at TabViewPagerPan.js:294)
    in RCTView (at View.js:71)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at TabViewPagerPan.js:284)
    in TabViewPagerPan (at TabView.js:165)
    in RCTView (at View.js:71)
    in View (at TabViewAnimated.js:252)
    in TabViewAnimated (at TabView.js:225)
    in TabView (at withCachedChildNavigation.js:66)
    in withCachedChildNavigation(TabView) (at TabNavigator.js:65)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:216)
    in NavigationContainer (at SceneView.js:31)
    in SceneView (at CardStack.js:405)
    in RCTView (at View.js:71)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at Card.js:26)
    in Card (at PointerEventsContainer.js:55)
    in Container (at CardStack.js:436)
    in RCTView (at View.js:71)
    in View (at CardStack.js:365)
    in RCTView (at View.js:71)
    in View (at CardStack.js:364)
    in CardStack (at CardStackTransitioner.js:97)
    in RCTView (at View.js:71)
    in View (at Transitioner.js:187)
    in Transitioner (at CardStackTransitioner.js:49)
    in CardStackTransitioner (at StackNavigator.js:60)
    in Unknown (at createNavigator.js:52)
    in Navigator (at createNavigationContainer.js:216)
    in NavigationContainer (at App.js:113)
    in RCTView (at View.js:71)
    in View (at App.js:111)
    in ThemeProvider (at App.js:110)
    in Provider (at App.js:109)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:102)
    in _class (at index.js:69)
    in RCTView (at View.js:71)
    in View (at index.js:68)
    in RootSiblingsWrapper (at AppContainer.js:119)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
  handleException	
  showDialog$1	
  logCapturedError	
  captureError	
  renderRoot	
  performWorkOnRoot	
  performWork	
  requestWork	
  scheduleWorkImpl	
  scheduleWork	
  enqueueSetState	
  Component.setState	
  (anonymous function)	
  (anonymous function)	
  __invokeCallback	
  (anonymous function)	
  __guardSafe	
  invokeCallbackAndReturnFlushedQueue

**This is my react-native info:**
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: ^16.2.0 => 16.3.2
  react-native: ^0.52.0 => 0.52.0

**And this is the component code where I'm using the menu:**

`import React from 'react';
import { ListItem, Button } from 'react-native-material-ui';
import Menu, { MenuItem, MenuDivider } from 'react-native-material-menu';

class Todo extends React.PureComponent {
    render() {
        return (
            <ListItem divider
                centerElement={{
                    primaryText: this.props.title,
                }}
                onPress={() => this.props.toogleComplete(this.props.doc.ref, this.props.complete)}
                leftElement={this.props.complete ? 'done' : 'undo'}
                rightElement={
                    <Menu ref={this.setMenuRef}
                          button={<Button onPress={this.showMenu} icon={'more-vert'} text={''}/>}
                    >
                        <MenuItem onPress={this.deleteAction}>eliminar</MenuItem>
                        <MenuDivider/>
                        <MenuItem onPress={this.toogleAction}>marcar</MenuItem>
                    </Menu>
                }
            />
        )
    }
    _menu = null
    setMenuRef = ref => {
        this._menu = ref
    }
    showMenu = () => {
        this._menu.show()
    }
    hideMenu = () => {
        this._menu.hide()
    }
    toogleAction = () => {
        this.props.toogleComplete(this.props.doc.ref, this.props.complete)
        this.hideMenu()
    }
    deleteAction = () => {
        this.props.delete(this.props.doc.ref)
        this.hideMenu()
    }
}
export default Todo`

Note: I got this error after I upgrade the react-netive-material-menu library to version 0.3.1, but when I use the 0.2.7 version everything works just fine. Is this a bug in the 0.3.1 version ?

Thanks in advance.

**Comment by mxck** [comment]
@yordanisgomez you have old version of react-native.
In readme you can see note about it
> ⚠️ Starting from version 0.3.0 minimum required react-native version is 0.54.

You can force use old version by `yarn add react-native-material-menu@~0.2.7` or `npm install --save  react-native-material-menu@~0.2.7`. Also you can upgrade your project by this [guide](https://facebook.github.io/react-native/docs/upgrading.html).
