### ISSUE TITLE
Warning when open menu

### ISSUE THREAD

**Issue by paolospag** [mxck/react-native-material-menu#22]
Hi,
I noticed a "little" bug when I open the menu.
The console reports this warning:

"Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks."

Any idea about this warning?

Thank you

**Comment by mxck** [comment]
This is react-native bug https://github.com/facebook/react-native/issues/18921#issuecomment-382727030
