### ISSUE TITLE
When I press the compass mode on react-native-maps the menu opens

### ISSUE THREAD

**Issue by h4m3d66** [mxck/react-native-material-menu#25]
I have a screen that on top it, it has material menu and on the bottom of it, it has google maps from react-native-maps. In this screen when I press the compass mode on google maps, the menu opens.

**Comment by mxck** [comment]
@h4m3d66 I did not understand your question. Can you give me some details?

**Comment by h4m3d66** [comment]
Sure,
This is my initial Screen:
![initial](https://user-images.githubusercontent.com/15716660/40921399-988a4cc4-6824-11e8-8727-ea481d140a51.jpg)
And this is the same screen when I press on compass:
![next](https://user-images.githubusercontent.com/15716660/40921442-b204fcda-6824-11e8-96bc-ee2e940fa916.jpg)
As it is showing, when I press on compass, somewhere else on top left of the screen also pressed and my menu opens!

**Comment by mxck** [comment]
I think issue in your layout.
If you press in this area menu is also shown?
![40921399-988a4cc4-6824-11e8-8727-ea481d140a51](https://user-images.githubusercontent.com/2190443/40928069-97314262-684a-11e8-9803-221499752653.jpg)

**Comment by h4m3d66** [comment]
No menu only opened when I press on compass

**Comment by mxck** [comment]
@h4m3d66 you fix this?

**Comment by h4m3d66** [comment]
no not fixed yet
