### ISSUE TITLE
On iOS when I navigate through the material menu from a chat window, the keyboard gets stuck on the screen.

### ISSUE THREAD

**Issue by Strafer14** [mxck/react-native-material-menu#27]
I have a chat component in which I have a right header component (through react navigation) that on click opens a material menu. In the menu I can navigate to a different screen, if I clicked on the text input and opened the keyboard, when I press on the right header component it closes the keyboard, but the moment I click to navigate to the other screen the keyboard comes back and is now stuck, when I type in it I see that it actually types in the text input from the previous (chat) screen.

When the right header component navigated directly to that page without the menu, this would not happend. Any ideas?

**Comment by mxck** [comment]
@Strafer14 sorry for late. You resolve your issue?
If not please can you post come minimal code example?
