### ISSUE TITLE
How to handle multiple menu in List.

### ISSUE THREAD

**Issue by suraj-epsumlabs** [mxck/react-native-material-menu#30]
I have a dynamic List. I want to open menu on button click in each list item.  How to do that?

**Comment by mxck** [comment]
You can write HOC wrapper with pass button component. Like <MyAwesomeMenu button={MyAwesomeListItem} /> or something like this.

**Comment by roshangm1** [comment]
Can you provide some sample code for this ?

**Comment by roshangm1** [comment]
I tried rendering the menu in each list item but when clicking the button, it will only show menu for the last item in the list whichever button you click.

**Comment by calle284** [comment]
Did you get a solution for this?
Because it is not working for me

**Comment by nishaQueppelin** [comment]
I am facing the same issue too
