### ISSUE TITLE
Unable to set MenuItem in fullwidth

### ISSUE THREAD

**Issue by paolospag** [mxck/react-native-material-menu#32]
Hi,
I tried to set my custom select Menu in fullwidth, but the items not seems to rendered correctly because their width is more or less half the main Menu.

In my Menu component, I do this:
```
...
<Menu
      ref={props.selectRef}
      style={{flex: 1, width: '100%'}}
...

```

and MenuItem:

```
...
<MenuItem style={{width: 100%}}></MenuItem>
...
```

Is there a way to fix this?
Can you provide a 'fullwidth' props option?

Thanks

**Comment by paolospag** [comment]
Any suggestions about this?
This is my problem:
![schermata 2018-07-06 alle 19 10 28](https://user-images.githubusercontent.com/35046292/42391685-7ef799d4-8150-11e8-8211-afd548120c6d.png)

**Comment by furedal** [comment]
Menu item is initially set to maxWidth: 248. You need to override it.

**Comment by mxck** [comment]
@paolospag yep, right now you need set `maxWidth` of MenuItem by `style` prop (like `<MenuItem style={{maxWidth:  500}} />. 
I think I need redesign this.
