### ISSUE TITLE
StatusBar appears whenever a menu opens

### ISSUE THREAD

**Issue by nicolasconnault** [mxck/react-native-material-menu#33]
I have an app that runs in full screen all the time, but when a react-native-material-menu is opened, the status bar appears at the top. Can this be prevented?

**Comment by mxck** [comment]
@nicolasconnault hi! Can you post some example?

**Comment by naveedshahji** [comment]
same issue on andriod with me.

**Comment by mxck** [comment]
@naveedshahji can you post some example?

**Comment by naveedshahji** [comment]
here is the code <View>
 
        <Menu
          ref={this.setMenuRef}
          button={<Text onPress={this.showMenu}>Settings</Text>}
        >
          <MenuItem onPress={this.hideMenu}>Settings</MenuItem>
          <MenuDivider />
          <MenuItem onPress={this.Logout}>Log Out</MenuItem>
        </Menu>
      </View>

**Comment by Jacky9425** [comment]
how about navigation bar on android? Currently my navigation bar is hidden natively but when the menu dropdown triggered for this package, the navigation is shown, and components covers by it is not able to respond onPress

**Comment by mxck** [comment]
@Jacky9425 @naveedshahji does the bug still exist in the last react-native? I just tested on virtual device and I can't catch this bug.
So if bug exists I will reopen this issue.

**Comment by oriharel** [comment]
The bug still exist. I'm running Expo SDK 35 which runs React Native 0.59.
