### ISSUE TITLE
Pass testID props to Menu and MenuItems

### ISSUE THREAD

**Issue by shaunsaker** [mxck/react-native-material-menu#34]
Hi guys,

Thanks for a cool menu.

Would you consider allowing passing of testID props to the Menu and MenuItem. This is useful for E2E testing with Detox. 

I realise this might be an edge use case and am happy to submit a PR.

Cheers,
Shaun

**Comment by mxck** [comment]
@shaunsaker hi! Yep, you can make PR.

**Comment by shaunsaker** [comment]
@mxck Thanks, much appreciated. I have opened a [PR](https://github.com/mxck/react-native-material-menu/issues/34).
