### ISSUE TITLE
Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by kolyneh** [mxck/react-native-material-menu#38]
Error occurred when running "npm install":
`node_modules\react-native-material-menu: Appears to be a git repo or submodule.`

Same error mentioned in [https://github.com/APSL/react-native-version-number/issues/13](url) ,
and reason maybe like `alexgvozden's` comment.

**Comment by osiellima** [comment]
Same problem here.

**Comment by mxck** [comment]
@kolyneh @osiellima check last 0.3.3 version.
