### ISSUE TITLE
Not able to view in IOS while pressing 

### ISSUE THREAD

**Issue by vijay2330** [mxck/react-native-material-menu#41]
Not showing menu in IOS while the onclick event fires..... Sometimes open but a very delayed response in IOS.......... Very diffcult to list the menuItems in IOS... Any suggestions?

**Comment by mxck** [comment]
@vijay2330 can you show example with code? You can also try make production build

**Comment by afshin-hoseini** [comment]
It's because of the `flexDirection` of it's hierarchy. It shouldn't be `row`.

For example the menu works on following code prefectly:

```
<View style={{flexDirection : "column", alignSelf:'stretch'}}>

            
            <Menu
                ref={this.setMenuRef}
                button={<IconButton icon="more-vert" onPress={()=>this.showMenu()}/> }>
                <MenuItem onPress={this.hideMenu}>Menu item 1</MenuItem>
            </Menu>
            
        </View>
```

But if I change the `flexDirection` to `row` it won't be shown.

**Comment by mxck** [comment]
@vijay2330 hi! This bug still exits? If it still exists I will reopen this issue.
