### ISSUE TITLE
Render icon + text in MenuItem

### ISSUE THREAD

**Issue by nicolasconnault** [mxck/react-native-material-menu#42]
Hi! 

Is it possible to render React components as well as a string in the MenuItem's children property?

Like this: https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F0B54x0KDcs5U-NC1tYmRKQWIzdDA%2Fbehavior-icon.png

When I try, I get an "Unexpected view type nested under text node".

**Comment by mxck** [comment]
@nicolasconnault hi!
Right now you need to create custom `MenuItem` component or you can use [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) that render icons as custom font (as text).

**Comment by nicolasconnault** [comment]
> @nicolasconnault hi!
> Right now you need to create custom `MenuItem` component or you can use [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) that render icons as custom font (as text).

Thanks @mxck, I'll try the custom MenuItem approach, it sounds good to me.

**Comment by BobsonTheFirst** [comment]
So how do you make a custom MenuItem?

**Comment by mxck** [comment]
@BobsonTheFirst hi! Right now you can pass icons (like react-native-vector-icons or expo icons) to MenuItem component.

So you can do something like this:
```jsx
import { Text } from 'react-native'

function MenuItemWithIcon({ icon, text, ...props }) {
  return (
    <MenuItem {...props}>
      <IconSet icon={icon}>
      <Text>{text}</Text>
    </MenuItem>
   );
}
```

You need just replace IconSet component with yours and add some styles, like margin after icon. :)

**Comment by BobsonTheFirst** [comment]
Hi, Thanks for your reply.

I got the icon working, but somehow i am unable to style. Color and fontSize are working, but for example margin isn't. Do you have a solution for that?

Btw, in your code you forgot a / in IconSet ;)

**Comment by mxck** [comment]
> I got the icon working, but somehow i am unable to style. Color and fontSize are working, but for example margin isn't. Do you have a solution for that?

Oh, sorry. Margin and padding doesn't work in text. Just add `{' '}` (space symbol) between icon and text. Like this ```<IconSet icon={icon}/>{` `}<Text>{text}</Text>```

> Btw, in your code you forgot a / in IconSet ;)

My bad, I try just type without tests :)

**Comment by BobsonTheFirst** [comment]
Some space between the icon and text is exactly what I did :D I hoped there was some other solution, but there isn't. So stick to my old solution ;) Thanks anyway :D

**Comment by papadi** [comment]
> Oh, sorry. Margin and padding doesn't work in text. Just add `{' '}` (space symbol) between icon and text. Like this `<IconSet icon={icon}/>{' '}<Text>{text}</Text>`

This is weird. The extra space will solve - in a non-elegant way  - the space issue between the icon and the text, but in my case, the icon and the text aren't properly aligned vertically. The icon has some padding at the bottom. Any idea how to fix this?

![image](https://user-images.githubusercontent.com/3359377/88546780-29139680-d01d-11ea-847f-60a46cc2462e.png)

**Comment by syedsaadqamar** [comment]
Facing the same vertical align issue
![image](https://user-images.githubusercontent.com/38069997/103922352-6dab6e00-5135-11eb-8c8c-c7a072450649.png)

**Comment by kramalexx** [comment]
Hi everyone. I managed to find a solution for proper vertical alignment of icon and text in MenuItem component.

Sample code:

`
// JSX code
<Menu ref={setMenuRef} button={Button}>
  <MenuItem style={[layouts.menuItem]} onPress={goToReports}>
    <View style={[s.px3, layouts.menuItemChild]}>
      <FeatherIcon name="edit" style={[s.textDark,]} size={18}/>
      <Text style={[typography.fontXs]}>{`   ${t("Mine oppdrag")}`}</Text>
    </View>
  </MenuItem>
  <MenuItem style={[layouts.menuItem]} onPress={goToProfile}>
    <View style={[s.px3, layouts.menuItemChild]}>
      <FeatherIcon name="user" style={[s.textDark]} size={18}/>
      <Text style={[typography.fontXs]}>{`   ${t("Min profil")}`}</Text>
    </View>
  </MenuItem>
</Menu>


// styles
menuItem: {
  height: 35,
},
menuItemChild: {
  height: 40,
  flexDirection: 'row',
  justifyContent: 'flex-start',
  alignItems: 'center'
}
`

So I added `<View/>` component inside `<MenuItem />` and set flex styles for it with setting height explicitly (even though there is said we don't have to set the height since version 0.68 - [take a look here](https://reactnative.dev/blog/2020/07/06/version-0.63#other-notable-improvements)  )

Also I set View height a bit more than MenuItem height to show proper click highlight without redundant offsets.

It works for me, but feel free to improve this approach 🙌🏾

**Comment by saif-o99** [comment]
@kramalexx your solution works perfectly but on RTL the menu items will not render, because of the wrapper view

**Comment by kramalexx** [comment]
@saif-o99 Thanks for the comment. I didn't test it with RTL because we don't need it yet. Do you have a universal solution for this case as well?

**Comment by saif-o99** [comment]
@kramalexx i removed the wrapper view and added it's style to the menu item style then they showed up. but still has this problem where i can't get the icons to be in one column on the left side
![image](https://user-images.githubusercontent.com/52207667/159464812-76d552c8-6067-474e-a113-5548ee63af5d.png)

on LTR it works fine
![image](https://user-images.githubusercontent.com/52207667/159464980-b6d70fd5-1201-4737-a97e-7147128b6e34.png)
