### ISSUE TITLE
Long item list opens up and doesn't show everything

### ISSUE THREAD

**Issue by nbastoWM** [mxck/react-native-material-menu#47]
I have this problem and I can't seem to be able to fix it:

![image](https://user-images.githubusercontent.com/15138821/49447610-e7dacd00-f7ce-11e8-9873-66d2a076eea9.png)

The menu opens up and doesn't show/scroll all the items.  The menu is inside in a scrollview.
The right popup menu is shorter so it shows everything.

![image](https://user-images.githubusercontent.com/15138821/49450179-638b4880-f7d4-11e8-867c-50fd947195e2.png)

Code:

```
<ScrollView contentContainerStyle={styles.container}>
( . . .)
<Menu
        ref={this.setMenuRef}
        button={
          <View style={{ flexDirection: "row" }}>
            <Text style={styles.popupMenuText} onPress={this.showMenu}>
              {this.props.title}
            </Text>
            <FontAwesome
              name={"caret-down"}
              size={17}
              color={colors.primary}
              style={{ padding: 0 }}
            />
          </View>
        }
      >
      
        <MenuItem onPress={() => this._onPress(null)}>
          {this.props.allTitle}
        </MenuItem>
        <MenuDivider />

        {this.props.options.map((item, index) => (
          <MenuItem
            key={`popupoption-${index}`}
            onPress={() => this._onPress(item)}
          >
            {item.title}
          </MenuItem>
        ))}
      </Menu>

( . . .)

</ScrollView>
```

**Comment by mxck** [comment]
@nbastoWM hi! If you need such a long menu, then most likely this component does not suit you :) Check iOS and android UI style guides.

For temporary fix you can just set `maxHeight` style prop.
Instead of this `style={{flex:1, height:this.props.options.length > 8 ? 400 : 'auto'}}` just try `style={{ maxHeight: 400 }}`
