### ISSUE TITLE
Failed prop type: Invalid prop `children` of type `object` supplied to `MenuItem`, expected `string`.

### ISSUE THREAD

**Issue by devahmadbarham** [mxck/react-native-material-menu#48]
Failed prop type: Invalid prop `children` of type `object` supplied to `MenuItem`, expected `string`.
i was try to get item from array but i have this error 
code
render {
  let citymenu = this.state.city.map((val, key) => {
          return     <MenuItem  key={key} onPress={()=> {this.state.cityselectname=val.name; }}><Text style={{color:'white'}}>  {val.name}</Text></MenuItem>  });

return {

<Menu  style={styles.menustyleopt} ref={this.setMenuRef}  button={
                    <Text style={styles.input}  onPress={this.showMenu}>{this.state.cityselectname || "select city"}</Text>  }    >
              {citymenu}
              </Menu>

}}

**Comment by mxck** [comment]
@devahmadbarham hi! Please send formatted code. :) Also check `textStyle` prop. You don't pass text  component to `MenuItem`
