### ISSUE TITLE
Menu is going out of view

### ISSUE THREAD

**Issue by mddanishansari** [mxck/react-native-material-menu#51]
This is my normal menu
![screenshot_1545202009](https://user-images.githubusercontent.com/11080523/50203908-07eebc80-0389-11e9-9366-31083a62ada9.png)

But if I open when menu button is below, the menu goes out of the view
![screenshot_1545201988](https://user-images.githubusercontent.com/11080523/50203944-248af480-0389-11e9-8b08-057c0d94f27a.png)

I have seen in preview that the menu can be anchored. Does it happens automatically? or we have to do it manually? If we have to do it manually there is nothing mentioned in the DOCS.

Thank you

**Comment by mxck** [comment]
@mddanishansari can you show code example at [snack](http://snack.expo.io)?

**Comment by AarshApple** [comment]
Any luck finding the solution !

**Comment by mxck** [comment]
@mddanishansari @chohonest does the bug still exist in the last react-native? I just tested on virtual device and I can't catch this bug.
So if bug exists I will reopen this issue.

**Comment by mxck** [comment]
Seems this RN bug https://github.com/facebook/react-native/issues/14887
