### ISSUE TITLE
Opening delay on iOS only

### ISSUE THREAD

**Issue by zoellex** [mxck/react-native-material-menu#53]
The menu works perfectly on Android, but now I tested it on iOS and it needs at least 10 seconds to open the menu (sometimes even longer). I also tried out to delete everything in the showMenu method because I thought maybe it slows it down on iOS, but same issue.

**Comment by ArthurKnoep** [comment]
I'm also having this issue but on Android. When I open the menu, it take up to 5 seconds to open.
However, I have not tested on iOS

**Comment by joselazarosiqueira** [comment]
Same problem on Android.

**Comment by eff-society** [comment]
I'm facing a similar issue on Android. The menu takes ~5 seconds to show up, but only the first time.

**Comment by mxck** [comment]
@zoellex @ArthurKnoep @joselazarosiqueira @eff-society did you try on real devices or emulator?
Just try on real devices or try use production mode.

If bug will still exits I will reopen issue.

**Comment by zoellex** [comment]
Actually I tried it on 3 different iPhones and iOS versions and it still doesn't work.

**Comment by mxck** [comment]
@zoellex can you post some code?

**Comment by mxck** [comment]
@zoellex did you try production mode also? Did you use JS chrome debugging?

**Comment by smartsuhani** [comment]
Was facing the same issue. If debug mode is on, try after stopping debug mode. It resolved in my case.

**Comment by bjh0501** [comment]
me too
same issue 

Screen Source

```
const InputPickMenu = () => {
  let refMenu = useRef(null);
 
  const setMenuRef = ref => {
    refMenu = ref;
  };
 
  const reportPopup = () => {
    refMenu.hide();
    NavigationService.navigate("Report", {
      reportedMemberNo: memberNo,
      reportedObjectFlag: "P",
      reportedObjectNo:memberNo
    })
  };

  const goChatting = () => {
    refMenu.hide();
    NavigationService.navigate("채팅")
  };
 
  const showMenu = () => {
    refMenu.show();
  };
   
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Menu
        ref={setMenuRef}
        button={
        <Icon
          name='dots-three-vertical'
          type='entypo'
          size={32}
          onPress={showMenu}
        />}
      >
        <MenuItem onPress={goChatting}>대화하기</MenuItem>
        <MenuItem onPress={reportPopup}>신고하기</MenuItem>
      </Menu>
    </View>
  );
}
```


Navigation source

```
<Stack.Screen
        name="InputPick"
        component={InputPick}
        options={{
          title: '',
          headerRight:(props)=>(
            <InputPickMenu/>
          )
        }}
      />
```

**Comment by cenaHara** [comment]
same issue,any solution ?

**Comment by cenaHara** [comment]
when turn on debug mode , menu show but i turn off debug or build release , menu no show
my code :  <View style={styles.viewMenu}>
          <Menu style={styles.menu} ref={menuRef} >
          {
            list.map((item, index) => {
              return  <MenuItem
                key={index}
                style={[styles.containStyle, ( index === list.length - 1 && styles.containStyleBottom )]}
                textStyle={styles.textStyle}
                onPress={() => onPressMenu(item,index)}>{item}</MenuItem>
            })
          }
        </Menu>
    </View>
