### ISSUE TITLE
Fantastic thank you!

### ISSUE THREAD

**Issue by Noitidart** [mxck/react-native-material-menu#6]
On Android I was trying to achieve this effect. I was using a hack on `<Picker mode="dropdown">` and it was a really bad experience. Thanks for this module!

**Comment by mxck** [comment]
@Noitidart 
![tenor](https://user-images.githubusercontent.com/2190443/33411223-edab72ce-d5b6-11e7-8e14-181b5d871776.gif)

**Comment by Noitidart** [comment]
:)
