### ISSUE TITLE
Menu Item width is hard coded.

### ISSUE THREAD

**Issue by hariramnandagopal** [mxck/react-native-material-menu#61]
Hey, 

Thanks for the plugin, it is really useful and got us over the line, However, I feel the Menu Item is being hardcoded and prevents the item to grow over `248px`, hence impacting the onPress.

File - `src/MenuItem.js` 
Location - `styles -> container -> maxWidth` [Line 79]

Current issue

![image](https://user-images.githubusercontent.com/10302158/59546836-d2adda80-8f77-11e9-8d08-f0d9f34acb7f.png)

After removing the `maxWidth` from the `MenuItem.js`

![image](https://user-images.githubusercontent.com/10302158/59546843-ec4f2200-8f77-11e9-82b2-0bcfdb643b95.png)

Any idea of being dynamic in the future or providing an option to accept the width as a separate prop?

I understand this repo is more of a `popup menu` rather than `dropdown`, however, having a dynamic width can be useful in both the scenarios. 

Regards
Hari

**Comment by mxck** [comment]
@hariramnandagopal you can pass `style` prop to `MenuItem` and set `maxWidth` to `auto` or `'100%'` like this:
```jsx
<MenuItem style={{ maxWidth: 'auto' }}>Engine Oil</MenuItem>
```
or you can write own component wrapper with `maxWidth: auto` or `maxWidth: '100%` like this:

```jsx
function DropdownItem({ style, ...props }} {
  return <MenuItem style={[{ maxWidth: 'auto' }, style]} />;
}
```

and use it like this:

```jsx
<DropdownItem>Engine Oil</DropdownItem>
```

This is good for you? :)

**Comment by hariramnandagopal** [comment]
Thanks @mxck this fixed the issue. Closing this issue.
