### ISSUE TITLE
Modal (Pop Up) after click on MenuItem

### ISSUE THREAD

**Issue by alyuid** [mxck/react-native-material-menu#68]
I want to share an interesting case. I am using this component for opening a modal screen, I mean a pop-up modal. If i click on a MenuItem it will be opened. It is working smoothly on Android but if i do that on IOS, it is not showing me that modal. So i tried so many variations and I solved it just like this

```
  toggleModal = () => {
    this.hideMenu();
    this.setState({ isModalVisible: !this.state.isModalVisible });
  };

  _menu = null;

  setMenuRef = ref => {
    this._menu = ref;
  };

  hideMenu = () => {
    this._menu.hide();
    this._menu.hide(); // THIS LINE
  };

  showMenu = () => {
    this._menu.show();
  };
  
  reportUser = () => {
    this.toggleModal();
    /**
     * report process
     */

  }
```

If i put a second this._menu.hide() line, it works. That looks so meaningless to me. Do you know what causes this?

**Comment by mxck** [comment]
@alyuid hi! This menu builded on modal and react-native have some problems with multiple opened modals.
In 0.6.5 I added onHidden callback to `hide()` method or you can pass onHidden prop to menu.
So you can do this:
```
this._menu.hide(() => this.setState({ isModalVisible: false});)
```

**Comment by DivyeshPonkiya** [comment]
Found solution to open menu item par modal. (iOS side)

complainModalHandel = () => {
    setTimeout(() => {
      this.setState({
        complaintReportVisible: !this.state.complaintReportVisible,
      });
    }, 500);
  };

render(
  <Menu
    visible={
      this.state.showMenu &&
      this.state.selectMatrimonialID == matrimonialProfileData.id
    }
    style={{
      borderRadius: ms(10),
    }}
    anchor={
      <Pressable
        style={{ padding: 4 }}
        onPress={() => {
          this.setState({
            showMenu: true,
            selectMatrimonialID: matrimonialProfileData.id,
          });
        }}
      >
        <Image
          source={require("../assets/images/ic_more.png")}
          style={styles.showMoreIcon}
        />
      </Pressable>
    }
    onRequestClose={() => {
      this.setState({ showMenu: false });
    }}
  >
    <MenuItem
      onPress={() => {
        this.complainModalHandel();
        this.setState({
          showMenu: false,
        });
      }}
    >
      <View style={styles.btnContainer}>
        <Image
          source={require("../assets/images/ic_flag.png")}
          style={styles.showMoreIcon}
        />
        <Text
          style={{
            ...styles.btnText,
            ...fontStyle.fontStyleRegularBold,
          }}
        >
          {'make complaint'}
        </Text>
      </View>
    </MenuItem>
  </Menu>

...
    <Modal
    transparent={true}
    animationType={'fade'}
    visible={this.state.complaintReportVisible}
    onRequestClose={() => {
        onClose();
    }}>
        <View style={styles.container}>
            ....
        </View>
    </Modal>
...
);

**Comment by DivyeshPonkiya** [comment]
Found solution to open menu item par modal. (iOS side)

https://github.com/mxck/react-native-material-menu/files/12333416/Menu.item.on.Modal.open.txt
