### ISSUE TITLE
onHidden is not a function

### ISSUE THREAD

**Issue by Krishna-Vyas** [mxck/react-native-material-menu#70]
If i click on the other parts of screen while menu is displayed, i found this error. Please check it and give me solution if it is.

TypeError: onHidden is not a function. (In 'onHidden()', 'onHidden' is an instance of Class)

**Comment by mxck** [comment]
@Krishna-Vyas fixed

**Comment by knapcio** [comment]
I just had a similar problem and realised I was doing a trivial mistake here. Sharing it in case somebody else has a similar problem:
I was passing the `hide` function directly to onPress:
`<MenuItem onPress={this.menuRef.hide}>`
The `hide` function signature is `function hide(onHidden) { ... }`
So basically if you pass the function directly to onPress it passes `event` from onPress and the function `hide` thinks it's `onHidden` argument.
The solution to this is obviously wrapping the `hide` function call in some other one:
`<MenuItem onPress={() => this.menuRef.hide()}>` or use a class method as in example.
