### ISSUE TITLE
Add example that can be run locally

### ISSUE THREAD

**Issue by mxck** [mxck/react-native-material-menu#75]
For testing purposes need add local example to repo using expo (if it possible) or react-native (by modify `metro.config.js`, like in [this](https://github.com/pietile/pietile-native-kit/tree/master/example) repo).

You can take an example from [README.md](https://github.com/mxck/react-native-material-menu/blob/master/README.md) or create own.

**Comment by anishkargaonkar** [comment]
I would like to work on this issue

**Comment by anishkargaonkar** [comment]
#80

**Comment by anishkargaonkar** [comment]
add example to locally test react-native-material-menu #80

**Comment by anishkargaonkar** [comment]
#80 **add example to locally test react-native-material-menu**
