### ISSUE TITLE
Bug on iOS when used with Alert

### ISSUE THREAD

**Issue by jonathanatn** [mxck/react-native-material-menu#78]
If a MenuItem fire an alert +  this.myMenuRef.hide();, it will freeze the complete UI of the app, probably because it close the menu and the alert in the same time

Example:
```
<MenuItem
    onPress={() => {
       this.setReminder('none');
       this.reminderMenu.hide();
     }}
     children={<Text>None</Text>}
 />
```

I also tried to switch the order of this.setReminder('none') and this.reminderMenu.hide()
But still problematic

A simple solution is to not hide the menu or hide it in the alert function but still a weird a behaviour

**Comment by mxck** [comment]
This known bug. Check https://github.com/mxck/react-native-material-menu/issues/68.
```this.reminderMenu.hide(() => this.setReminder('none'));)```

**Comment by AmitPandya007** [comment]
@mxck 
this issue is with Android as well. When on MenuItem alert is called.
