### ISSUE TITLE
When I open the menu the status bar disappears - Android

### ISSUE THREAD

**Issue by goncalo-msrt** [mxck/react-native-material-menu#8]
On Android when I open the menu the status bar of the devices disappears, is this a wanted behaviour? happens just to me?

Thanks in advance

**Comment by mxck** [comment]
@goncalo-msrt no, this is not wanted behavior. Please can you post some code example? Also react-native version and device info would be helpful! :)

**Comment by goncalo-msrt** [comment]
Just using your example happens.
android 7, oneplus 5t. react-native 0.49, gonna do more tests

**Comment by mxck** [comment]
@goncalo-msrt try fix this in next week :)

**Comment by goncalo-msrt** [comment]
So you could see the same issue?

**Comment by mxck** [comment]
No, but I try recrate it on my Android phone, but only on next week:smiley:

**Comment by mxck** [comment]
@goncalo-msrt I can't recreate this is issue on my device :\

**Comment by dragonStandard123** [comment]
Same issue

OS : Android O,
react-native : 0.59.5
react-native-material-menu: ^0.4.2
