### ISSUE TITLE
Not able to show view after doing an action from MenuItem

### ISSUE THREAD

**Issue by Harsh2402** [mxck/react-native-material-menu#84]
When I click on MenuItem, then I am sowing alert dialog, then once the menu will hide, after pressing a MenuItem, then for the few secs, an alert is showing and then it also closed, as the model will close.

I have used this inside the Row component of Flatlist.

```
<Menu ...>
           <MenuItem 
                     onPress={() => {
                           alert("My View")
                           hideMenu()
                     }}>Click Me
           </MenuItem>
</Menu>
```

**Comment by m-gautam** [comment]
Found any solution fro this @Harsh2402

**Comment by mxck** [comment]
This known bug. Check #68.
