### ISSUE TITLE
Can you do an example to switch navigation?

### ISSUE THREAD

**Issue by pherm** [mxck/react-native-material-menu#9]

**Comment by mxck** [comment]
@pherm can you give a more complete description?

**Comment by pherm** [comment]
@mxck yeah. I want to add two page screen (i use react navigation), can you explain how to do with your package?

**Comment by pherm** [comment]
My code don't job! 👇👇
//
import { NavigationActions } from 'react-navigation'

//
const { navigation } = this.props;

//...
<MenuItem onPress={this.hideMenu}>SCREEN 1</MenuItem>
<MenuItem onPress={() => this.props.navigation.navigate("screen2")}>SCREEN 2</MenuItem>

**Comment by mxck** [comment]
@pherm can you show full code?

**Comment by pherm** [comment]
@mxck i attach it!
[test_nav.txt](https://github.com/mxck/react-native-material-menu/files/1595182/test_nav.txt)

**Comment by pherm** [comment]
@mxck man, I'm waiting for your feedback!

**Comment by mxck** [comment]
@pherm sorry for waiting :) For this kind of questions you need to use https://stackoverflow.com

**Comment by pherm** [comment]
dude, your feedback, now, It is useless!
