### ISSUE TITLE
using menu in a flat list, the menu is shown at the location of the last menu button even i press on any other menu item

### ISSUE THREAD

**Issue by omarelnakib** [mxck/react-native-material-menu#90]

**Comment by nishaQueppelin** [comment]
I am also facing the same issue. Any Suggestions?

**Comment by alz10** [comment]
Same Issue here

**Comment by Roocha-T** [comment]
![Screenshot 2021-02-02 at 4 58 24 PM](https://user-images.githubusercontent.com/75784036/106594469-253a7100-6578-11eb-8f4a-9be7868f5bfa.png)
