### ISSUE TITLE
TouchableHighlight error on start up

### ISSUE THREAD

**Issue by kapilpau** [mxck/react-native-material-menu#93]
When I try and run my app in development mode, I get an error saying:

```js
TypeError: undefined is not an object (evaluating '_reactNative.TouchableHighlight.propTypes.style')
```

When I go to the [demo](https://snack.expo.io/@mxck/react-native-material-menu-demo), there's a similar error as well:
```js
l.TouchableNativeFeedback.SelectableBackground is not a function
```

**Comment by mxck** [comment]
@kapilpau did you run in `web`?

**Comment by rdgoutiyama** [comment]
editing `/node_modules/react-native-material-menu/src/MenuItem.js`

**removing**

`

MenuItem.propTypes = {
  children: PropTypes.string.isRequired,
  disabled: PropTypes.bool,
  disabledTextColor: PropTypes.string,
  onPress: PropTypes.func,
  style: TouchableHighlight.propTypes.style,
  textStyle: Text.propTypes.style,
  underlayColor: TouchableHighlight.propTypes.underlayColor,
};

`

works, or editing:

`

MenuItem.propTypes = {
  children: PropTypes.string.isRequired,
  disabled: PropTypes.bool,
  disabledTextColor: PropTypes.string,
  onPress: PropTypes.func,
  textStyle: Text.propTypes.style,
};

`

works too..

In React Native 0.62+ proptypes was depracated.

**Comment by kapilpau** [comment]
> @kapilpau did you run in `web`?

@mxck what do you mean?

**Comment by rdgoutiyama** [comment]
> When I try and run my app in development mode, I get an error saying:
> 
> ```js
> TypeError: undefined is not an object (evaluating '_reactNative.TouchableHighlight.propTypes.style')
> ```
> 
> When I go to the [demo](https://snack.expo.io/@mxck/react-native-material-menu-demo), there's a similar error as well:
> 
> ```js
> l.TouchableNativeFeedback.SelectableBackground is not a function
> ```

Upgrading to v1.1.3 works.
