### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNative.TouchableHighlight.propTypes.style'

### ISSUE THREAD

**Issue by vikil143** [mxck/react-native-material-menu#95]
I got this error at react-native-material-menu when upgrading my react native version 61.5 to 63.2 I not getting how to solve this error any help, please

Actually this error says react-native TouchableHighlight undefined at MenuItem below code base at MenuItem.js file
`MenuItem.propTypes = {
  children: PropTypes.node.isRequired,
  disabled: PropTypes.bool,
  disabledTextColor: PropTypes.string,
  ellipsizeMode: PropTypes.string,
  onPress: PropTypes.func,
  style: TouchableHighlight.propTypes.style,
  textStyle: Text.propTypes.style,
  underlayColor: TouchableHighlight.propTypes.underlayColor,
};`

## Environment

System:
OS: Linux 5.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
CPU: (4) x64 Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
Memory: 1.96 GB / 15.47 GB
Shell: 4.4.20 - /bin/bash
Binaries:
Node: 13.10.1 - ~/.nvm/versions/node/v13.10.1/bin/node
Yarn: Not Found
npm: 6.14.5 - ~/.nvm/versions/node/v13.10.1/bin/npm
Watchman: Not Found
SDKs:
Android SDK: Not Found
IDEs:
Android Studio: Not Found
Languages:
Java: 1.8.0_265 - /usr/bin/javac
Python: 2.7.17 - /usr/bin/python
npmPackages:
@react-native-community/cli: Not Found
react: 16.13.1 => 16.13.1
react-native: 0.63.2 => 0.63.2
npmGlobalPackages:
react-native: Not Found

**Comment by vikil143** [comment]
Any help please

**Comment by mxck** [comment]
@vikil143 please check your material-menu-version.
It must be actual (v1.1.3)

**Comment by vikil143** [comment]
Its version (v1.0.0)

**Comment by mxck** [comment]
Upgrade to actual version.
