### ISSUE TITLE
Proposal: Use react-native-reanimated for 60FPS animations.

### ISSUE THREAD

**Issue by ammarahm-ed** [mxck/react-native-material-menu#98]
Hello, thanks for this amazing library.

I would like to propose using [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) for native 60FPS animations. I have migrated to it in [my fork](https://github.com/ammarahm-ed/react-native-material-menu) and it is working perfectly. Let me know if this is something you are willing to add here and I will make a pull request.

**Comment by mxck** [comment]
Hi!
Cool job, but I would like to leave this package without any native dependencies :).
Thank you!

**Comment by ammarahm-ed** [comment]
Ok, sounds good.
